name: hummingbot-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - boto3
  - libcxx                
  - libta-lib>=0.6.4
  - python-dotenv
  - pandas>=2.3.2
  - numba>=0.61.2
  - numpy>=2.2.6
  - pandas-ta>=0.4.71b
  - ta-lib>=0.6.4
  - tqdm>=4.67.1
  - docker-py
  - pip
  - pip:
      - msgpack>=1.0.5
      - flake8
      - isort
      - pre-commit
      - logfire
      - logfire[fastapi]
      - logfire[system-metrics]
      - paho-mqtt>=2.1.0
      - aiomqtt>=2.0.0
      - sqlalchemy>=2.0.0
      - asyncpg
      - psycopg2-binary
      - greenlet
      - pydantic-settings
